### ISSUE TITLE
نمایش لیست ارائه‌ها به همراه نام ارائه دهنده در توضیحات کوتاه گزارشات

### ISSUE THREAD

**Issue by bijanebrahimi** [mashhadlug/next#4]
‫در پیاده‌سازی دریافت summary از مقاله‌ها، از وجود تگ‌های مربوطه مانند `<!-- more -->` استفاده شود. همچنین در صورت امکان لیست ارائه‌های جلسه که با تگ heading 2 مشخص شده اند را در انتهای summary نمایش داده شود

**Comment by tuxitop** [comment]
نمی‌دونم چی تو ذهنته دقیقا ولی من یه فیلتر برای جینجا نوشتم که این کار رو انجام بده. در حال حاضر خیلی از گزارش‌ها تگی که تو گفتی رو ندارن. به هر حال اگه مشکلی بود این رو دوباره باز کن.
