### ISSUE TITLE
‫بارگزاری صفحات به صورت Ajax درست کار نمی‌کند

### ISSUE THREAD

**Issue by bijanebrahimi** [mashhadlug/next#8]
‫در صفحه گزارشات، دکمه «مشاهده بیشتر» که وظیفه دریافت گزارشات صفحه بعدی به صورت Ajax و درج کردن آن در صفحه را دارد، هر بار موارد تکراری را نیز به صفحه اضافه می‌کند. این موارد تکراری در صفحات بعدی، عملا رکوردهای بسیار زیادی را به صفحه اضافه میکند

**Comment by tuxitop** [comment]
این هم فکر می‌کنم مشکل رو حل کرده باشه. اگر مشکلی بود دوباره بازش کن.
